# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojKZZQw-CeSGqyxWeG4brMU3F3p4GCzM
"""

!git clone https://github.com/Cleunio/CompleteProject.git

# Commented out IPython magic to ensure Python compatibility.
# %cd CompleteProject

!git status
!git add .
!git commit -m "Update notebooks and experiments"
!git push

!git add .
!git commit -m "Update notebook"
!git push

!git config --global user.name "Cleunio"
!git config --global user.email "cleuniofranca@gmail.com"

!ls
!echo "# CompleteProject" > README.md
!git add .
!git commit -m "Initial commit"
!git branch

!git branch -M main
!git push -u origin main

!git config --global user.name "Cleunio"
!git config --global user.email "cleuniofranca@gmail.com"

!git config --global --unset credential.helper
!rm -f ~/.git-credentials
!git config --global credential.helper store

!git branch -M main

!git remote remove origin || true
!git remote add origin https://github.com/Cleunio/CompleteProject.git

# Primeiro push com autenticação via token

pip install mlflow

!pip install pyngrok

import pandas as pd
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import mlflow
from mlflow.models import infer_signature

## set the tracking uri
mlflow.set_tracking_uri(uri="http://127.0.0.1:5000")

mlflow ui

from pyngrok import ngrok
import os

get_ipython().system_raw(
    "mlflow ui --backend-store-uri file:/content/mlruns --port 5000 &"
)

public_url = ngrok.connect(5000)
print(public_url)

import os

os.environ["MLFLOW_TRACKING_URI"] = "file:/content/mlruns"

import mlflow

mlflow.set_tracking_uri("file:/content/mlruns")
mlflow.set_experiment("MLFlow Quickstart")

print("Tracking URI:", mlflow.get_tracking_uri())

##load the dataset
X,y=datasets.load_iris(return_X_y=True)
#split the data into training and test sets
X_Train, X_Test, y_Train, y_Test=train_test_split(X,y,test_size=0.20)

#define the model hyperparameters
params = {"penalty": "l2", "solver":"lbfgs", "max_iter":1000, "multi_class":"auto", "random_state":8888}

lr = LogisticRegression(**params)
lr.fit(X_Train, y_Train)

## Prediction on the test set
y_pred=lr.predict(X_Test)
y_pred
accuracy = accuracy_score(y_Test, y_pred)
print(accuracy)

mlflow.set_tracking_uri("file:/content/mlruns")
mlflow.set_experiment("MLFlow Quickstart")

mlflow.set_experiment("MLFlow Quickstart")

with mlflow.start_run():

    # log dos hiperparâmetros
    mlflow.log_params(params)

    # log da métrica
    mlflow.log_metric("accuracy", accuracy)

    # tag informativa
    mlflow.set_tag("Train info", "Logistic Regression - Iris data")

    # assinatura do modelo
    signature = infer_signature(X_Train, lr.predict(X_Train))

    # log do modelo
    model_info = mlflow.sklearn.log_model(
        sk_model=lr,
        name="iris_model",                 # substitui artifact_path
        signature=signature,
        input_example=X_Train,
        registered_model_name="Tracking_quickstart"
    )

!git log --oneline --max-count=3

# Commented out IPython magic to ensure Python compatibility.
# %cd CompleteProject

!git status

!git add .

!git commit -m "Update MLflow experiment and notebooks"

!git push

"""#LOAD THE MODEL BACK FOR PREDICTION AS A GENERIC PYTHON FUNCTION MODEL"""

loaded_model=mlflow.pyfunc.load_model(model_info.model_uri)
predictions=loaded_model.predict(X_Test)

iris_feature_names = datasets.load_iris().feature_names
result=pd.DataFrame(X_Test,columns=iris_feature_names)
result["actual_class"]=y_Test
result["predicted_class"]=predictions
result.head()

# Commented out IPython magic to ensure Python compatibility.
# %cd sample_data

!git status

!git add .

!git commit -m "Update MLflow experiment and notebooks"

!git push

!git status

from google.colab import drive
drive.mount('/content/drive')

!ls /content/CompleteProject

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CompleteProject

!git status
!git add main.ipynb
!git commit -m "Add MLflow notebook from Colab"
!git push -u origin main

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CompleteProject
!git config --global credential.helper store

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CompleteProject
!git remote remove origin